version: '3.8'

services:
  youtube-summarizer:
    build: .
    container_name: youtube-summarizer
    ports:
      - "8000:8000"
    volumes:
      - temp_files:/app/temp
      - app_logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=host.docker.internal:11434  # For bridge networking
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Ensures host.docker.internal works

volumes:
  temp_files:
    driver: local
  app_logs:
    driver: local

# This configuration uses bridge networking with host.docker.internal
# to access your existing Ollama container
# 
# Access the application at: http://localhost:8000
#
# To use this configuration:
# docker-compose -f docker-compose.bridge.yml up --build
