version: '3.8'

services:
  youtube-summarizer:
    build: .
    container_name: youtube-summarizer
    ports:
      - "8000:8000"
    volumes:
      - temp_files:/app/temp
      - app_logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=host.docker.internal:11434  # Change this to your Ollama container host
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    network_mode: "host"  # Use host networking to access external Ollama

volumes:
  temp_files:
    driver: local
  app_logs:
    driver: local

# Alternative network configuration for existing Ollama container:
# If your Ollama container is on a specific network, use this instead:
#
# networks:
#   default:
#     external:
#       name: your-existing-ollama-network
#
# And update the environment variable:
# environment:
#   - OLLAMA_HOST=your-ollama-container:11434
