services:
  youtube-summarizer:
    build: .
    container_name: youtube-summarizer
    ports:
      - "8000:8000"  # This will show in docker ps
    volumes:
      - temp_files:/app/temp
      - app_logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=host.docker.internal:11434  # For bridge networking
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    # Memory limits
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    # GPU configuration
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Ensures host.docker.internal works

volumes:
  temp_files:
    driver: local
  app_logs:
    driver: local

# For GPU support, run with: docker compose --profile gpu up --build
# Or use the docker run command with --gpus all flag
# The environment variables above will enable GPU detection when available
