services:
  youtube-summarizer:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: youtube-summarizer
    ports:
      - "8000:8000"
    volumes:
      - temp_files:/app/temp
      - app_logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=host.docker.internal:11434
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  temp_files:
    driver: local
  app_logs:
    driver: local
