services:
  youtube-summarizer:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: youtube-summarizer
    ports:
      - "8000:8000"  # This will show in docker ps
    volumes:
      - temp_files:/app/temp
      - app_logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - OLLAMA_HOST=host.docker.internal:11434  # For bridge networking
      - FORCE_CPU=true  # Force CPU mode
    restart: unless-stopped
    # CPU-only configuration - no GPU devices
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Ensures host.docker.internal works

volumes:
  temp_files:
    driver: local
  app_logs:
    driver: local

# CPU-only configuration for systems without GPU support
# This removes all GPU-related configurations while maintaining
# the same functionality on CPU hardware
